### ISSUE TITLE
Encounter with error in DDP

### ISSUE THREAD

**Issue by Yuuuuuuuuuuuuuuuuuummy** [kekmodel/MPL-pytorch#10]
Nice work! But I meet a strange issue when I use multi-GPUs.
Specifically, the code is the same and it works well in a single GPU. But when I run it on multi-GPUS using DDP. I meet an error

> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128]] is at version 4; expected version 3 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

Does anybody meet the same issue? Hope to get your reply! thx!!

**Comment by Yuuuuuuuuuuuuuuuuuummy** [comment]
It seems that the code should use nn.ReLU() instead of nn.ReLU(inplace=True). But when I change this, it doesn't work!

**Comment by Yuuuuuuuuuuuuuuuuuummy** [comment]
BTW, I have no idea about what the 'version' refers to?

**Comment by AdorableYoyo** [comment]
I have the same issue!! RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by kekmodel** [comment]
Please check the requirements.
